version: "3"

services: 
  izanami-backend_prod:
    container_name: izanami-backend_prod
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./backend:/backend
      - ./batch_scheduler.py:/batch_scheduler.py


  izanami-front_prod:
    container_name: izanami-front_prod
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: nginx -g "daemon off;"
    ports:
      - 80:80
    volumes:
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - izanami-backend_prod

  izanami-mysql:
    container_name: izanami-mysql
    build: ./db/
    restart: always
    env_file: 
      - ./db/.env
    environment: 
      MYSQL_USER: izanami
      MYSQL_ROOT_PASSWORD: izanami
      MYSQL_DATABASE: db_izanami
      TZ: "Asia/Tokyo"
    command: mysqld
    cap_add:
      - SYS_NICE
    volumes: 
      - ./db/mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/dump.sql:/dump.sql


