# 本番環境
FROM node:lts-alpine as build-stage
WORKDIR /frontend
COPY frontend/package*.json ./
RUN npm install --no-optional
COPY ./frontend .
RUN npm run build

# 本番環境
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /dist /usr/share/nginx/html
