version: "3"

services: 
  izanami-backend:
    container_name: izanami-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py
    ports: 
      - 5000:5000
    volumes:
      - ./backend:/backend

  izanami-front:
    container_name: izanami-front
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/frontend

