version: "3"

services: 
  flask:
    container_name: flask-dev
    image: flask-dev
    ports: 
      - 3000:5000
    volumes: 
      - ./app:/backend_app

  vue:
    container_name: vue-dev
    image: vue-dev
    ports: 
      - 8080:8080
    volumes: 
      - ./frontend:/app
