FROM python:3.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

COPY . .
WORKDIR /backend

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -r /backend/requirements_prod.txt

WORKDIR /