version: "3"

services: 
  izanami-backend:
    container_name: izanami-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      TZ: "Asia/Tokyo"
    command: python manage.py
    ports: 
      - 5000:5000
    volumes:
      - ./backend:/backend
      - ./batch_scheduler.py:/batch_scheduler.py

  izanami-front:
    container_name: izanami-front
    init: true
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    environment:
      TZ: "Asia/Tokyo"
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/frontend

  izanami-mysql:
    container_name: izanami-mysql
    build: ./db/
    restart: always
    hostname: izanami-mysql
    env_file: 
      - ./db/.env
    environment: 
      MYSQL_USER: izanami
      MYSQL_ROOT_PASSWORD: izanami
      MYSQL_DATABASE: db_izanami
      TZ: "Asia/Tokyo"
      BIND-ADDRESS: 0.0.0.0
    command: mysqld
    cap_add:
      - SYS_NICE
    volumes: 
      - ./db/mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
